spring:
  banner:
    location: banner/practicelibBanner.txt
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    name: bibliootus
    url: jdbc:h2:mem:bibliootus
  data:
    mongodb:
      database: bibliootus
