;
CREATE USER IF NOT EXISTS SA SALT 'fcea1e13b9ddf489' HASH '1f8d89b013b01262d3a8d493949ecc2ee7a8f7ff492b758017c55a20b0e890d2' ADMIN;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8D321FB0_D991_4CFF_AA8D_9F6FDB01A822 START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_37F52579_F22A_4A36_98D1_798F073B3CDC START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1BA94989_8517_442A_B2DD_1391417A5999 START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE PUBLIC.GENRES
(
  ID   INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_37F52579_F22A_4A36_98D1_798F073B3CDC) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_37F52579_F22A_4A36_98D1_798F073B3CDC,
  NAME VARCHAR(255)
);
ALTER TABLE PUBLIC.GENRES
  ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY (ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GENRES;  
CREATE CACHED TABLE PUBLIC.BOOKS
(
  ID       INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_1BA94989_8517_442A_B2DD_1391417A5999) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_1BA94989_8517_442A_B2DD_1391417A5999,
  NAME     VARCHAR(255)                                                                             NOT NULL,
  GENRE_ID INT                                                                                      NOT NULL
);
ALTER TABLE PUBLIC.BOOKS
  ADD CONSTRAINT PUBLIC.CONSTRAINT_3 PRIMARY KEY (ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BOOKS;   
CREATE CACHED TABLE PUBLIC.AUTHORS
(
  ID   INT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_8D321FB0_D991_4CFF_AA8D_9F6FDB01A822) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_8D321FB0_D991_4CFF_AA8D_9F6FDB01A822,
  NAME VARCHAR(255)                                                                             NOT NULL
);
ALTER TABLE PUBLIC.AUTHORS
  ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY (ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.AUTHORS; 
CREATE CACHED TABLE PUBLIC.AUTHOR_TO_BOOK_MAP
(
  AUTHOR_ID INT NOT NULL,
  BOOK_ID   INT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.AUTHOR_TO_BOOK_MAP;      
ALTER TABLE PUBLIC.AUTHOR_TO_BOOK_MAP
  ADD CONSTRAINT PUBLIC.CONSTRAINT_D8A UNIQUE (AUTHOR_ID, BOOK_ID);
ALTER TABLE PUBLIC.GENRES
  ADD CONSTRAINT PUBLIC.CONSTRAINT_7D UNIQUE (NAME);
ALTER TABLE PUBLIC.BOOKS
  ADD CONSTRAINT PUBLIC.CONSTRAINT_3C UNIQUE (NAME);
ALTER TABLE PUBLIC.AUTHORS
  ADD CONSTRAINT PUBLIC.CONSTRAINT_44 UNIQUE (NAME);
ALTER TABLE PUBLIC.AUTHOR_TO_BOOK_MAP
  ADD CONSTRAINT PUBLIC.CONSTRAINT_D FOREIGN KEY (AUTHOR_ID) REFERENCES PUBLIC.AUTHORS (ID) NOCHECK;
ALTER TABLE PUBLIC.BOOKS
  ADD CONSTRAINT PUBLIC.CONSTRAINT_3C7 FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRES (ID) NOCHECK;
ALTER TABLE PUBLIC.AUTHOR_TO_BOOK_MAP
  ADD CONSTRAINT PUBLIC.CONSTRAINT_D8 FOREIGN KEY (BOOK_ID) REFERENCES PUBLIC.BOOKS (ID) NOCHECK;
